---
- hosts: target_group
  become: yes
  become_user: root
  tasks:
    - name: Install Kustomize
      command: snap install kustomize

    - name: Apply Meilisearch Manifest File
      command: kustomize build . | kubectl apply -f -
